# Generated by Django 4.1 on 2022-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='TUser image')),
                ('name', models.CharField(max_length=30, verbose_name='TUser name')),
                ('about', models.CharField(max_length=30, verbose_name='TUser about')),
            ],
            options={
                'verbose_name': 'TUser',
                'verbose_name_plural': 'TUsers',
            },
        ),
    ]
